name: CI - Snapshot
run-name: CI snapshot disparada por ${{ github.actor }}

on:   
  # inicia o workflow manualmente
  workflow_dispatch:
jobs:  
 build_back:
    name: Build Back
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o repositório
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: build
      - name: Compila o(s) projeto(s)
        shell: bash
        run: |
          cd build/ci_cd_projeto/backend
          npm install
          npm run build

  build_front:
    name: Build Front
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o repositório
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: build
      - name: Compila o(s) projeto(s)
        shell: bash
        run: |
          cd build/ci_cd_projeto/frontend
          npm install
          npm run build
