name: CI - Snapshot
run-name: CI snapshot disparada por ${{ github.actor }}

on:   
  # inicia o workflow manualmente
  workflow_dispatch:
jobs:  
 build_back:
    name: Build Back
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o repositório
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: build
      - name: Compila o(s) projeto(s)
        shell: bash
        run: |
          cd build/ci_cd_projeto/backend
          npm install
          npm run build
      - name: Compacta(Zip) buid
        shell: bash
        run: |
          cd build/ci_cd_projeto/backend
          zip -r backend.zip dist
 build_front:
    name: Build Front
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o repositório
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          path: build
      - name: Compila o(s) projeto(s)
        shell: bash
        run: |
          cd build/ci_cd_projeto/frontend
          npm install
          npm run build
      - name: Compacta(Zip) buid
        shell: bash
        run: |
          cd build/ci_cd_projeto/frontend
          zip -r frontend.zip dist

 empacotar:
    name: Empacotar
    needs: [build_back, build_front]
    runs-on: ubuntu-latest
    steps:
     - name: Criar Versão / Release e Tag
       uses: softprops/action-gh-release@v2
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         body: Release
         tag_name: Release
         fail_on_unmatched_files: true
         files: backend.zip,frontend.zip
